export const FETCH_PATIENTS = "FETCH_PATIENTS";
export const SET_PATIENTS = "SET_PATIENTS";

export const SUBMIT_PATIENT_FORM = "SUBMIT_PATIENT_FORM";
export const QUEUE_PATIENT_FORM = "QUEUE_PATIENT_FORM";

export const FETCH_PATIENT_DETAILS = "FETCH_PATIENT_DETAILS";
export const SET_PATIENT_DETAILS = "SET_PATIENT_DETAILS";

export const SET_PATIENTS_LOADING = "SET_PATIENTS_LOADING";
export const SET_DETAILS_LOADING = "SET_DETAILS_LOADING";
export const SET_ERROR = "SET_ERROR";

export const NETWORK_ONLINE = "NETWORK_ONLINE";
export const NETWORK_OFFLINE = "NETWORK_OFFLINE";



